Component.create(:id=>1, :name => "Component-1", :domain => "Distributed")
Component.create(:id=>2, :name => "Component-2", :domain => "Distributed")
Component.create(:id=>3, :name => "Component-3", :domain => "Distributed")
Component.create(:id=>4, :name => "Component-4", :domain => "Workplaces")
Component.create(:id=>5, :name => "Component-5", :domain => "Distributed")
