Software.create(:id=>1, :maker => 'IBM', :sw_name => 'WAS', :version => '6.0', :eos_date => Date.today)
Software.create(:id=>2, :maker => 'Microsoft', :sw_name => 'Sharepoint', :version => '4.0', :eos_date => '2016-03-21')
Software.create(:id=>3, :maker => 'Oracle', :sw_name => 'WebLogic', :version => '111.0', :eos_date => '2019-08-11')
Software.create(:id=>4, :maker => 'Citrix', :sw_name => 'XenApp', :version => '6.5', :eos_date => '2100-08-11')
Software.create(:id=>5, :maker => 'RedHat', :sw_name => 'JBoss Enterprise Application Platform', :version => '6.0', :eos_date => '2017-08-11')
