Component.create(:id=>0, :name=>"Internal Service (IIS-1) common", :domain=>"Distributed")
Component.create(:id=>1, :name=>"Internal Service (IIS-2) cif,nbwf", :domain=>"Distributed")
Component.create(:id=>2, :name=>"Internal Service (IIS-3) pdwf", :domain=>"Distributed")
Component.create(:id=>3, :name=>"Global Intranet Edge Server", :domain=>"Distributed")
Component.create(:id=>4, :name=>"External Service (IHS-1) internet", :domain=>"Distributed")
Component.create(:id=>5, :name=>"External Service (IHS-2) nttgw", :domain=>"Distributed")
Component.create(:id=>6, :name=>"External Service (IHS-3) HP", :domain=>"Distributed")
Component.create(:id=>7, :name=>"External Service (IHS-4) annex", :domain=>"Distributed")
Component.create(:id=>8, :name=>"External Service (IHS-5) mypage", :domain=>"Distributed")
Component.create(:id=>9, :name=>"CSG for Meta Navi", :domain=>"Distributed")
Component.create(:id=>10, :name=>"WAS-Extarnal", :domain=>"Distributed")
Component.create(:id=>11, :name=>"WAS-Internal", :domain=>"Distributed")
Component.create(:id=>12, :name=>"QS,MDM-CIF", :domain=>"Distributed")
Component.create(:id=>13, :name=>"WAS-My AXA", :domain=>"Distributed")
Component.create(:id=>14, :name=>"WAS-NBWF", :domain=>"Distributed")
Component.create(:id=>15, :name=>"Siebel-Web", :domain=>"Distributed")
Component.create(:id=>16, :name=>"FileNet-PDWF", :domain=>"Distributed")
Component.create(:id=>17, :name=>"WHS HATS", :domain=>"Distributed")
Component.create(:id=>18, :name=>"WPS", :domain=>"Distributed")
Component.create(:id=>19, :name=>"JBOSS-CRM", :domain=>"Distributed")
Component.create(:id=>20, :name=>"CXP for Meta Navi", :domain=>"Distributed")
Component.create(:id=>21, :name=>"Apache for HP", :domain=>"Distributed")
Component.create(:id=>22, :name=>"App server(Other)", :domain=>"Distributed")
Component.create(:id=>23, :name=>"SVF", :domain=>"Distributed")
Component.create(:id=>24, :name=>"CANON", :domain=>"Distributed")
Component.create(:id=>25, :name=>"e-Mail(SMTP)", :domain=>"Distributed")
Component.create(:id=>26, :name=>"EAI(Ext-SOAP)", :domain=>"Distributed")
Component.create(:id=>27, :name=>"EAI(Int-SOAP)", :domain=>"Distributed")
Component.create(:id=>28, :name=>"EAI(eGate)", :domain=>"Distributed")
Component.create(:id=>29, :name=>"EAI(rProxy)", :domain=>"Distributed")
Component.create(:id=>30, :name=>"ETL", :domain=>"Distributed")
Component.create(:id=>31, :name=>"Oracle DB", :domain=>"Distributed")
Component.create(:id=>32, :name=>"MS SQL DB", :domain=>"Distributed")
Component.create(:id=>33, :name=>"ESG", :domain=>"Distributed")
Component.create(:id=>34, :name=>"EDI", :domain=>"Distributed")
Component.create(:id=>35, :name=>"MQ", :domain=>"Distributed")
Component.create(:id=>36, :name=>"Shared File Server", :domain=>"Distributed")
Component.create(:id=>37, :name=>"Shared File Server for NBWF", :domain=>"Distributed")
Component.create(:id=>38, :name=>"CIF-Terminal", :domain=>"Distributed")
Component.create(:id=>39, :name=>"DR", :domain=>"Distributed")
Component.create(:id=>40, :name=>"Mail Relay", :domain=>"Distributed")
Component.create(:id=>41, :name=>"SFTP server", :domain=>"Distributed")
Component.create(:id=>42, :name=>"JOB", :domain=>"Distributed")
Component.create(:id=>43, :name=>"Extarnal DNS, NTP of Tier1", :domain=>"Distributed")
Component.create(:id=>44, :name=>"Extarnal and Global DNS, NTP of Tier2", :domain=>"Distributed")
Component.create(:id=>45, :name=>"Shared FTP Server", :domain=>"Distributed")
Component.create(:id=>46, :name=>"Others", :domain=>"Distributed")
Component.create(:id=>47, :name=>"AD External", :domain=>"Distributed")
Component.create(:id=>48, :name=>"AD Internal", :domain=>"Distributed")
Component.create(:id=>49, :name=>"MF", :domain=>"Distributed")
Component.create(:id=>50, :name=>"AS400", :domain=>"Distributed")
