ComponentServer.create(:id=>1, :component_id => 1, :server_id=> 1)
ComponentServer.create(:id=>2, :component_id => 1, :server_id=> 2 )
ComponentServer.create(:id=>3, :component_id => 2, :server_id=> 3 )
ComponentServer.create(:id=>4, :component_id => 2, :server_id=> 4 )
ComponentServer.create(:id=>5, :component_id => 3, :server_id=> 2 )
ComponentServer.create(:id=>6, :component_id => 4, :server_id=> 3 )
ComponentServer.create(:id=>7, :component_id => 5, :server_id=> 1 )
ComponentServer.create(:id=>7, :component_id => 5, :server_id=> 2 )
ComponentServer.create(:id=>7, :component_id => 5, :server_id=> 3 )
ComponentServer.create(:id=>7, :component_id => 5, :server_id=> 4 )
ComponentServer.create(:id=>7, :component_id => 5, :server_id=> 5 )
