ServiceComponent.create(:id=>1, :service_id => 1, :component_id=> 1)
ServiceComponent.create(:id=>2, :service_id => 1, :component_id=> 2 )
ServiceComponent.create(:id=>3, :service_id => 2, :component_id=> 3 )
ServiceComponent.create(:id=>4, :service_id => 2, :component_id=> 4 )
ServiceComponent.create(:id=>5, :service_id => 3, :component_id=> 2 )
ServiceComponent.create(:id=>6, :service_id => 4, :component_id=> 3 )
ServiceComponent.create(:id=>7, :service_id => 5, :component_id=> 1 )
ServiceComponent.create(:id=>8, :service_id => 5, :component_id=> 2 )
ServiceComponent.create(:id=>9, :service_id => 5, :component_id=> 3 )
ServiceComponent.create(:id=>10, :service_id => 5, :component_id=> 4 )
ServiceComponent.create(:id=>11, :service_id => 5, :component_id=> 5 )
