Service.create(:id=>1, :name=>"ND21 Accounting", :sid=>"10010", :code=>"xx", :description=>"Description of ND21 Accounting")
Service.create(:id=>2, :name=>"SAP FI", :sid=>"10020", :code=>"xx", :description=>"Description of SAP FI")
Service.create(:id=>3, :name=>"Suspense Receipts Administration", :sid=>"10030", :code=>"xx", :description=>"Description of Suspense Receipts Administration")
Service.create(:id=>4, :name=>"Disbursement", :sid=>"10040", :code=>"xx", :description=>"Description of Disbursement")
Service.create(:id=>5, :name=>"i-win Collection and Disbursement", :sid=>"10050", :code=>"xx", :description=>"Description of i-win Collection and Disbursement")
Service.create(:id=>6, :name=>"ND21 Actuarial and Statistics", :sid=>"10060", :code=>"xx", :description=>"Description of ND21 Actuarial and Statistics")
Service.create(:id=>7, :name=>"Group Life Actuarial and Statistics", :sid=>"10070", :code=>"xx", :description=>"Description of Group Life Actuarial and Statistics")
Service.create(:id=>8, :name=>"i-win Actuarial", :sid=>"10080", :code=>"xx", :description=>"Description of i-win Actuarial")
Service.create(:id=>9, :name=>"Investment Management", :sid=>"10090", :code=>"xx", :description=>"Description of Investment Management")
Service.create(:id=>10, :name=>"i-win Investment", :sid=>"10100", :code=>"xx", :description=>"Description of i-win Investment")
Service.create(:id=>11, :name=>"Fundweb-I", :sid=>"10110", :code=>"xx", :description=>"Description of Fundweb-I")
Service.create(:id=>12, :name=>"Navi+ Agreement", :sid=>"10120", :code=>"xx", :description=>"Description of Navi+ Agreement")
Service.create(:id=>13, :name=>"QIT New Business (Web Online)", :sid=>"10130", :code=>"xx", :description=>"Description of QIT New Business (Web Online)")
Service.create(:id=>14, :name=>"QIT Underwriting Workflow", :sid=>"10140", :code=>"xx", :description=>"Description of QIT Underwriting Workflow")
Service.create(:id=>15, :name=>"ND21 New Business", :sid=>"10150", :code=>"xx", :description=>"Description of ND21 New Business")
Service.create(:id=>16, :name=>"i-win New Business", :sid=>"10160", :code=>"xx", :description=>"Description of i-win New Business")
Service.create(:id=>17, :name=>"Customer Customer-Based Process and Information Management", :sid=>"10170", :code=>"xx", :description=>"Description of Customer Customer-Based Process and Information Management")
Service.create(:id=>18, :name=>"Danposhin Policy Admin", :sid=>"10180", :code=>"xx", :description=>"Description of Danposhin Policy Admin")
Service.create(:id=>19, :name=>"ND21 Policy Admin", :sid=>"10190", :code=>"xx", :description=>"Description of ND21 Policy Admin")
Service.create(:id=>20, :name=>"Customer Mutual Aid", :sid=>"10200", :code=>"xx", :description=>"Description of Customer Mutual Aid")
Service.create(:id=>21, :name=>"i-win Policy Admin", :sid=>"10210", :code=>"xx", :description=>"Description of i-win Policy Admin")
Service.create(:id=>22, :name=>"(Former) Variable Life Insurance", :sid=>"10220", :code=>"xx", :description=>"Description of (Former) Variable Life Insurance")
Service.create(:id=>23, :name=>"Group Whole Life Insurance Policy Admin", :sid=>"10230", :code=>"xx", :description=>"Description of Group Whole Life Insurance Policy Admin")
Service.create(:id=>24, :name=>"Whole Life Insurance by Single Payment at Retirement", :sid=>"10240", :code=>"xx", :description=>"Description of Whole Life Insurance by Single Payment at Retirement")
Service.create(:id=>25, :name=>"Asset-Accumulating Savings Policy Admin", :sid=>"10250", :code=>"xx", :description=>"Description of Asset-Accumulating Savings Policy Admin")
Service.create(:id=>26, :name=>"Qualified Annuity Policy Admin", :sid=>"10260", :code=>"xx", :description=>"Description of Qualified Annuity Policy Admin")
Service.create(:id=>27, :name=>"Fire Mutual Policy Admin", :sid=>"10270", :code=>"xx", :description=>"Description of Fire Mutual Policy Admin")
Service.create(:id=>28, :name=>"Old Individual Medical Policy Admin", :sid=>"10280", :code=>"xx", :description=>"Description of Old Individual Medical Policy Admin")
Service.create(:id=>29, :name=>"Operational Efficiency Workflow", :sid=>"10290", :code=>"xx", :description=>"Description of Operational Efficiency Workflow")
Service.create(:id=>30, :name=>"QIT Surrender Application Printing (Web Online)", :sid=>"10300", :code=>"xx", :description=>"Description of QIT Surrender Application Printing (Web Online)")
Service.create(:id=>31, :name=>"Tokyo CCI Billing", :sid=>"10310", :code=>"xx", :description=>"Description of Tokyo CCI Billing")
Service.create(:id=>32, :name=>"OE First Premium Collection via Convenience Store", :sid=>"10320", :code=>"xx", :description=>"Description of OE First Premium Collection via Convenience Store")
Service.create(:id=>33, :name=>"(Former) Variable Life Insurance", :sid=>"10330", :code=>"xx", :description=>"Description of (Former) Variable Life Insurance")
Service.create(:id=>34, :name=>"ND21 Collection", :sid=>"10340", :code=>"xx", :description=>"Description of ND21 Collection")
Service.create(:id=>35, :name=>"Damposhin Collection", :sid=>"10350", :code=>"xx", :description=>"Description of Damposhin Collection")
Service.create(:id=>36, :name=>"CAN Collection", :sid=>"10360", :code=>"xx", :description=>"Description of CAN Collection")
Service.create(:id=>37, :name=>"Payment Web", :sid=>"10370", :code=>"xx", :description=>"Description of Payment Web")
Service.create(:id=>38, :name=>"QIT Claims Workflow", :sid=>"10380", :code=>"xx", :description=>"Description of QIT Claims Workflow")
Service.create(:id=>39, :name=>"ND21 Claims", :sid=>"10390", :code=>"xx", :description=>"Description of ND21 Claims")
Service.create(:id=>40, :name=>"Damposhin Claims", :sid=>"10400", :code=>"xx", :description=>"Description of Damposhin Claims")
Service.create(:id=>41, :name=>"Annuitant Administration", :sid=>"10410", :code=>"xx", :description=>"Description of Annuitant Administration")
Service.create(:id=>42, :name=>"Annuity Valuation", :sid=>"10420", :code=>"xx", :description=>"Description of Annuity Valuation")
Service.create(:id=>43, :name=>"Business Performance", :sid=>"10430", :code=>"xx", :description=>"Description of Business Performance")
Service.create(:id=>44, :name=>"Sales Reps Management", :sid=>"10440", :code=>"xx", :description=>"Description of Sales Reps Management")
Service.create(:id=>45, :name=>"Recruit Management System (RMS)", :sid=>"10460", :code=>"xx", :description=>"Description of Recruit Management System (RMS)")
Service.create(:id=>46, :name=>"Agency Management", :sid=>"10470", :code=>"xx", :description=>"Description of Agency Management")
Service.create(:id=>47, :name=>"Life Advisor Management", :sid=>"10480", :code=>"xx", :description=>"Description of Life Advisor Management")
Service.create(:id=>48, :name=>"Customer Database", :sid=>"10490", :code=>"xx", :description=>"Description of Customer Database")
Service.create(:id=>49, :name=>"Information Database", :sid=>"10500", :code=>"xx", :description=>"Description of Information Database")
Service.create(:id=>50, :name=>"Market Administration", :sid=>"10510", :code=>"xx", :description=>"Description of Market Administration")
Service.create(:id=>51, :name=>"Lead Management Tool(LMT,CIS)", :sid=>"10520", :code=>"xx", :description=>"Description of Lead Management Tool(LMT,CIS)")
Service.create(:id=>52, :name=>"Navi+ Proposal", :sid=>"10530", :code=>"xx", :description=>"Description of Navi+ Proposal")
Service.create(:id=>53, :name=>"Web Proposal Illustration Tool (Japan Post)", :sid=>"10540", :code=>"xx", :description=>"Description of Web Proposal Illustration Tool (Japan Post)")
Service.create(:id=>54, :name=>"Surrender and Lapse (Counterproposal for S&L)", :sid=>"10550", :code=>"xx", :description=>"Description of Surrender and Lapse (Counterproposal for S&L)")
Service.create(:id=>55, :name=>"Customer Web Portal", :sid=>"10560", :code=>"xx", :description=>"Description of Customer Web Portal")
Service.create(:id=>56, :name=>"Agent Gateway Portal", :sid=>"10570", :code=>"xx", :description=>"Description of Agent Gateway Portal")
Service.create(:id=>57, :name=>"Bancassuarance Portal (AXA Support Web)", :sid=>"10580", :code=>"xx", :description=>"Description of Bancassuarance Portal (AXA Support Web)")
Service.create(:id=>58, :name=>"BancaAdmin", :sid=>"10580", :code=>"xx", :description=>"Description of BancaAdmin")
Service.create(:id=>59, :name=>"Data Transfer to NTT Gateway and ISS", :sid=>"10590", :code=>"xx", :description=>"Description of Data Transfer to NTT Gateway and ISS")
Service.create(:id=>60, :name=>"Siebel Contact Center", :sid=>"10600", :code=>"xx", :description=>"Description of Siebel Contact Center")
Service.create(:id=>61, :name=>"ANNEX eBusiness", :sid=>"10620", :code=>"xx", :description=>"Description of ANNEX eBusiness")
Service.create(:id=>62, :name=>"ND21 Access Privilege Administration", :sid=>"10640", :code=>"xx", :description=>"Description of ND21 Access Privilege Administration")
Service.create(:id=>63, :name=>"Memorandum Administration", :sid=>"10650", :code=>"xx", :description=>"Description of Memorandum Administration")
Service.create(:id=>64, :name=>"Form Supply", :sid=>"10660", :code=>"xx", :description=>"Description of Form Supply")
Service.create(:id=>65, :name=>"Fixed Assets (ProPlus)", :sid=>"10670", :code=>"xx", :description=>"Description of Fixed Assets (ProPlus)")
Service.create(:id=>66, :name=>"Employee Payroll", :sid=>"10680", :code=>"xx", :description=>"Description of Employee Payroll")
Service.create(:id=>67, :name=>"HR Survey", :sid=>"10690", :code=>"xx", :description=>"Description of HR Survey")
Service.create(:id=>68, :name=>"AXA Homepage", :sid=>"10700", :code=>"xx", :description=>"Description of AXA Homepage")
Service.create(:id=>69, :name=>"AIS - Agent Information System (Agent Producer DB)", :sid=>"10710", :code=>"xx", :description=>"Description of AIS - Agent Information System (Agent Producer DB)")
Service.create(:id=>70, :name=>"First Contact Resolution", :sid=>"10720", :code=>"xx", :description=>"Description of First Contact Resolution")
Service.create(:id=>71, :name=>"Ariba Procurement Management", :sid=>"10730", :code=>"xx", :description=>"Description of Ariba Procurement Management")
Service.create(:id=>72, :name=>"Data Transfer to AXA-BS", :sid=>"10740", :code=>"xx", :description=>"Description of Data Transfer to AXA-BS")
Service.create(:id=>73, :name=>"D-Binder Electronic Filing System", :sid=>"10750", :code=>"xx", :description=>"Description of D-Binder Electronic Filing System")
Service.create(:id=>74, :name=>"BI Data Warehouse and Datamart", :sid=>"10760", :code=>"xx", :description=>"Description of BI Data Warehouse and Datamart")
Service.create(:id=>75, :name=>"Claims Support(W-entry,PIS.PSS)", :sid=>"10770", :code=>"xx", :description=>"Description of Claims Support(W-entry,PIS.PSS)")
Service.create(:id=>76, :name=>"Customer Information File (CIF)", :sid=>"10780", :code=>"xx", :description=>"Description of Customer Information File (CIF)")
Service.create(:id=>77, :name=>"Product Rate Calculation", :sid=>"10790", :code=>"xx", :description=>"Description of Product Rate Calculation")
Service.create(:id=>78, :name=>"Life-J New Business", :sid=>"10800", :code=>"xx", :description=>"Description of Life-J New Business")
Service.create(:id=>79, :name=>"Life-J Policy Admin", :sid=>"10810", :code=>"xx", :description=>"Description of Life-J Policy Admin")
Service.create(:id=>80, :name=>"Life-J Collection", :sid=>"10820", :code=>"xx", :description=>"Description of Life-J Collection")
Service.create(:id=>81, :name=>"Life-J Claims", :sid=>"10830", :code=>"xx", :description=>"Description of Life-J Claims")
Service.create(:id=>82, :name=>"Life-J Actuarial & Statistics", :sid=>"10840", :code=>"xx", :description=>"Description of Life-J Actuarial & Statistics")
Service.create(:id=>83, :name=>"Life-J Accounting", :sid=>"10850", :code=>"xx", :description=>"Description of Life-J Accounting")
Service.create(:id=>84, :name=>"Life-J Annuity Payouts", :sid=>"10860", :code=>"xx", :description=>"Description of Life-J Annuity Payouts")
Service.create(:id=>85, :name=>"Life-J Agency Management", :sid=>"10870", :code=>"xx", :description=>"Description of Life-J Agency Management")
Service.create(:id=>86, :name=>"Life-J Business Performance & Commission", :sid=>"10880", :code=>"xx", :description=>"Description of Life-J Business Performance & Commission")
Service.create(:id=>87, :name=>"Life-J Customer Information", :sid=>"10890", :code=>"xx", :description=>"Description of Life-J Customer Information")
Service.create(:id=>88, :name=>"Agent Web (AFL)", :sid=>"10910", :code=>"xx", :description=>"Description of Agent Web (AFL)")
Service.create(:id=>89, :name=>"Customer Web (AFL)", :sid=>"10920", :code=>"xx", :description=>"Description of Customer Web (AFL)")
Service.create(:id=>90, :name=>"AdminTool (AFL)", :sid=>"10920", :code=>"xx", :description=>"Description of AdminTool (AFL)")
Service.create(:id=>91, :name=>"UnitPrice Display (AFL)", :sid=>"10920", :code=>"xx", :description=>"Description of UnitPrice Display (AFL)")
Service.create(:id=>92, :name=>"Re-insurance Application (AFL)", :sid=>"10950", :code=>"xx", :description=>"Description of Re-insurance Application (AFL)")
Service.create(:id=>93, :name=>"ANSER / U-line Web (AFL)", :sid=>"10970", :code=>"xx", :description=>"Description of ANSER / U-line Web (AFL)")
Service.create(:id=>94, :name=>"Salesforce contact Center (AFL)", :sid=>"11000", :code=>"xx", :description=>"Description of Salesforce contact Center (AFL)")
Service.create(:id=>95, :name=>"Claim Payment Workflow", :sid=>"11020", :code=>"xx", :description=>"Description of Claim Payment Workflow")
Service.create(:id=>96, :name=>"Salesforce contact Center", :sid=>"11030", :code=>"xx", :description=>"Description of Salesforce contact Center")
Service.create(:id=>97, :name=>"Ms Dynamics contact Center (AG/Corp)", :sid=>"11040", :code=>"xx", :description=>"Description of Ms Dynamics contact Center (AG/Corp)")
Service.create(:id=>98, :name=>"New Business Underwriting Workflow", :sid=>"11050", :code=>"xx", :description=>"Description of New Business Underwriting Workflow")
Service.create(:id=>99, :name=>"Taxable Annuity amount calculation tool", :sid=>"11060", :code=>"xx", :description=>"Description of Taxable Annuity amount calculation tool")
Service.create(:id=>100, :name=>"GT AIA Annuity payment management", :sid=>"11070", :code=>"xx", :description=>"Description of GT AIA Annuity payment management")
Service.create(:id=>101, :name=>"BI Separate a/c auto reconciliation", :sid=>"11080", :code=>"xx", :description=>"Description of BI Separate a/c auto reconciliation")
Service.create(:id=>102, :name=>"BI SPI & Sales activity Reporting", :sid=>"11090", :code=>"xx", :description=>"Description of BI SPI & Sales activity Reporting")
Service.create(:id=>103, :name=>"BI CCI Performance Simulation", :sid=>"11100", :code=>"xx", :description=>"Description of BI CCI Performance Simulation")
Service.create(:id=>104, :name=>"People Soft Human Resources Management", :sid=>"11130", :code=>"xx", :description=>"Description of People Soft Human Resources Management")
Service.create(:id=>105, :name=>"PeopleIn Global Human Resources Management", :sid=>"11140", :code=>"xx", :description=>"Description of PeopleIn Global Human Resources Management")
Service.create(:id=>106, :name=>"ND21 Human Resources Interface", :sid=>"11150", :code=>"xx", :description=>"Description of ND21 Human Resources Interface")
Service.create(:id=>107, :name=>"BI In-force Management - Persistency and S&LP", :sid=>"11160", :code=>"xx", :description=>"Description of BI In-force Management - Persistency and S&LP")
Service.create(:id=>108, :name=>"Salesforce contact Center - FI Sales Tracking", :sid=>"11170", :code=>"xx", :description=>"Description of Salesforce contact Center - FI Sales Tracking")
Service.create(:id=>109, :name=>"BI Direct marketing sales dashboard", :sid=>"11180", :code=>"xx", :description=>"Description of BI Direct marketing sales dashboard")
Service.create(:id=>110, :name=>"BI sales channel Compensation statement", :sid=>"11190", :code=>"xx", :description=>"Description of BI sales channel Compensation statement")
Service.create(:id=>111, :name=>"Daptiv Project Portfolio Management", :sid=>"11200", :code=>"xx", :description=>"Description of Daptiv Project Portfolio Management")
Service.create(:id=>112, :name=>"Salesforce Complaint Management", :sid=>"11210", :code=>"xx", :description=>"Description of Salesforce Complaint Management")
Service.create(:id=>113, :name=>"i-win Annuity payment management", :sid=>"11220", :code=>"xx", :description=>"Description of i-win Annuity payment management")
Service.create(:id=>114, :name=>"Call  Center Telephony System", :sid=>"11230", :code=>"xx", :description=>"Description of Call  Center Telephony System")
Service.create(:id=>115, :name=>"AML Screening Managemennt", :sid=>"11240", :code=>"xx", :description=>"Description of AML Screening Managemennt")
Service.create(:id=>116, :name=>"Credit Card Payment Data Interface", :sid=>"11250", :code=>"xx", :description=>"Description of Credit Card Payment Data Interface")
Service.create(:id=>117, :name=>"Salesforce Sales Activity Management", :sid=>"11260", :code=>"xx", :description=>"Description of Salesforce Sales Activity Management")
Service.create(:id=>118, :name=>"Customer MyPage", :sid=>"11270", :code=>"xx", :description=>"Description of Customer MyPage")
Service.create(:id=>119, :name=>"Daiwa Securities Data Interface", :sid=>"11280", :code=>"xx", :description=>"Description of Daiwa Securities Data Interface")
Service.create(:id=>120, :name=>"Lotus Global Intranet", :sid=>"11290", :code=>"xx", :description=>"Description of Lotus Global Intranet")
Service.create(:id=>121, :name=>"BI HR Employee Reporting and Analysis", :sid=>"11300", :code=>"xx", :description=>"Description of BI HR Employee Reporting and Analysis")
