Server.create(:id=>0, :host_name=>"wjbwww0t01", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>1, :host_name=>"wjbwww0t02", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>2, :host_name=>"wjbwww0j01", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>3, :host_name=>"wjbwww0j02", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>4, :host_name=>"wjbwww1a01", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>5, :host_name=>"wjbwww1a02", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>6, :host_name=>"LJCWAS37", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>7, :host_name=>"LJCWAS38", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>8, :host_name=>"axnd-l-hq-101", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>9, :host_name=>"axnd-l-hq-201", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>10, :host_name=>"axws-l-hq-101", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>11, :host_name=>"axws-l-hq-201", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>12, :host_name=>"axnd-l-hq-111", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>13, :host_name=>"axnd-l-hq-211", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>14, :host_name=>"axws-l-hq-111", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>15, :host_name=>"axws-l-hq-211", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>16, :host_name=>"ljawww0b01", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>17, :host_name=>"ljawww0b02", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>18, :host_name=>"ljawww0b03", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>19, :host_name=>"ljawww0b04", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>20, :host_name=>"ljawww0b05", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>21, :host_name=>"ljawas33", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>22, :host_name=>"ljawas34", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>23, :host_name=>"ljawww37", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>24, :host_name=>"ljawww38", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>25, :host_name=>"ljawas24", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>26, :host_name=>"ljawas25", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>27, :host_name=>"ljawww35", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>28, :host_name=>"ljawww36", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>29, :host_name=>"AXWS-M-HQ-004", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>30, :host_name=>"AXWS-M-HQ-104(Standby)", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>31, :host_name=>"AXWS-M-HQ-002", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>32, :host_name=>"AXWS-M-HQ-102(Standby)", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>33, :host_name=>"wJAcxg06(DR)", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>34, :host_name=>"wJAcxg07(DR)", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>35, :host_name=>"LJBwas06", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>36, :host_name=>"LJBwas07", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>37, :host_name=>"LJBwas12", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>38, :host_name=>"LJBwas13", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>39, :host_name=>"axap-l-mel-002P", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>40, :host_name=>"axap-l-mel-001P", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>41, :host_name=>"axap-l-mel-003P", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>42, :host_name=>"axap-l-mel-103P", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>43, :host_name=>"ljbwas26", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>44, :host_name=>"ljbwas27", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>45, :host_name=>"WJBWAS19", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>46, :host_name=>"WJBWAS20", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>47, :host_name=>"LJCWWW44", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>48, :host_name=>"WJBFNT19", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>49, :host_name=>"WJBFNT20", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>50, :host_name=>"WJBFNT21", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>51, :host_name=>"WJBFNT22", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>52, :host_name=>"wJCfnt0c01", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>53, :host_name=>"wJCfnt0c02", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>54, :host_name=>"LJBwhs02", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>55, :host_name=>"LJBwhs03", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>56, :host_name=>"LJBwpo02", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>57, :host_name=>"LJBwpo03", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>58, :host_name=>"wJBcxp04", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>59, :host_name=>"wJBcxp05", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>60, :host_name=>"wJBcxp06", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>61, :host_name=>"wJBcxp07", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>62, :host_name=>"wJBcxp08", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>63, :host_name=>"wJBcxp09", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>64, :host_name=>"wJBcxp10", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>65, :host_name=>"wJBcxp11", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>66, :host_name=>"wJBcxp14", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>67, :host_name=>"LJBwww0w01", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>68, :host_name=>"LJBwww0w02", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>69, :host_name=>"wJBapp10", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>70, :host_name=>"wJBapp11", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>71, :host_name=>"wJBimg03", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>72, :host_name=>"wJBimg04", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>73, :host_name=>"AXWS-M-MEL-020", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>74, :host_name=>"AXWS-M-MEL-010", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>75, :host_name=>"AXWS-M-MEL-110", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>76, :host_name=>"AXAP-M-MEL-010", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>77, :host_name=>"AXAP-M-MEL-020", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>78, :host_name=>"AXRP-L-MEL-010", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>79, :host_name=>"LJBETL13", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>80, :host_name=>"IJAPRX0C01", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>81, :host_name=>"IJKPRX0C02", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>82, :host_name=>"EDIServ", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>83, :host_name=>"EDIServ-CS(Cold Standby)", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>84, :host_name=>"LJBMSG00", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>85, :host_name=>"LJCfsr13", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>86, :host_name=>"wJCfsr10", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>87, :host_name=>"wJBetL09", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>88, :host_name=>"LJAWWW11", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>89, :host_name=>"LJAWWW12", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>90, :host_name=>"LJAWWW13", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>91, :host_name=>"LJAWWW14", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>92, :host_name=>"RPROXY", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>93, :host_name=>"LJBMRS03", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>94, :host_name=>"LJAFTP01", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>95, :host_name=>"LJCJOB04", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>96, :host_name=>"LJCJOB05", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>97, :host_name=>"LJADNS00", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>98, :host_name=>"LJADNS01", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>99, :host_name=>"LJADNS02", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>100, :host_name=>"LJADNS03", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>101, :host_name=>"AXS-HFTP-01", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>102, :host_name=>"AXMS-L-HQ-001", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>103, :host_name=>"AXSP-L-HQ-001", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>104, :host_name=>"AXMS-L-HQ-010", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>105, :host_name=>"LJCCAI03", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>106, :host_name=>"LJCLOG04", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>107, :host_name=>"ljcsec00", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>108, :host_name=>"LJCZBX00", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>109, :host_name=>"axms-l-hq-003", :p_or_v=>"v", :os=>"RedHat Enterprise Linux")
Server.create(:id=>110, :host_name=>"WJBADS20", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>111, :host_name=>"WJBADS21", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>112, :host_name=>"WJLADS22", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>113, :host_name=>"WJLADS23", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>114, :host_name=>"WJBADS14", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>115, :host_name=>"WJBADS15", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>116, :host_name=>"WJCADM05", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>117, :host_name=>"WJCADS03", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>118, :host_name=>"WJCADS04", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>119, :host_name=>"WJCADS05", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>120, :host_name=>"WJCADS06", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>121, :host_name=>"WJCADS12", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>122, :host_name=>"WJCADS13", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>123, :host_name=>"WJLADS18", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>124, :host_name=>"WJLADS19", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>125, :host_name=>"WJMADS16", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
Server.create(:id=>126, :host_name=>"WJMADS17", :p_or_v=>"v", :os=>"MS Windows Server 2008R2")
